<#
.SYNOPSIS
    Creates a "Build Dashboard.lnk" shortcut on the Windows Desktop.

.DESCRIPTION
    Run this script once to create the desktop shortcut.
    The shortcut is self-contained and can be copied/moved anywhere.

    What this script does:
      1. Generates the custom amber-gear icon (build/builder_icon.ico) via
         build/make_icon.py using Pillow. Falls back to a system icon if
         Pillow is unavailable.
      2. Creates "Build Dashboard.lnk" on the Desktop (or -Destination path).

    Double-clicking the shortcut will:
      - Start the Build Dashboard Flask server on port 5001 (minimised)
      - Open the dashboard automatically in Google Chrome (or default browser)

    To STOP the server, click the "Build Dashboard Server" button in the taskbar
    and close that window (or press Ctrl+C inside it).

.NOTES
    If you move the job_tracker folder, re-run this script to update the shortcut.
#>

param(
    [string]$ShortcutName = "Build Dashboard",
    [string]$Destination  = [Environment]::GetFolderPath("Desktop")
)

# ── Paths ─────────────────────────────────────────────────────────────────────

$ScriptDir    = Split-Path -Parent $MyInvocation.MyCommand.Definition
$LauncherPs1  = Join-Path $ScriptDir "start_builder.ps1"
$ShortcutPath = Join-Path $Destination "$ShortcutName.lnk"
$IconFile     = Join-Path $ScriptDir "build\builder_icon.ico"
$MakeIconPy   = Join-Path $ScriptDir "build\make_icon.py"

Write-Host ""
Write-Host "  Build Dashboard - Desktop Shortcut Creator" -ForegroundColor Cyan
Write-Host "  -------------------------------------------" -ForegroundColor DarkGray
Write-Host ""

# ── Validate launcher ─────────────────────────────────────────────────────────

if (-not (Test-Path $LauncherPs1)) {
    Write-Host "  [ERROR] start_builder.ps1 not found in:" -ForegroundColor Red
    Write-Host "          $ScriptDir" -ForegroundColor Red
    Write-Host ""
    Read-Host "  Press Enter to exit"
    exit 1
}

if (-not (Test-Path $Destination)) {
    Write-Host "  [ERROR] Destination folder does not exist:" -ForegroundColor Red
    Write-Host "          $Destination" -ForegroundColor Red
    Write-Host ""
    Read-Host "  Press Enter to exit"
    exit 1
}

# ── Generate custom icon ──────────────────────────────────────────────────────

function Find-Python {
    foreach ($cmd in @("python", "py")) {
        $found = Get-Command $cmd -ErrorAction SilentlyContinue
        if ($found) { return $found.Source }
    }
    return $null
}

if (-not (Test-Path $IconFile)) {
    Write-Host "  Generating icon (build/builder_icon.ico)..." -ForegroundColor DarkGray
    if (Test-Path $MakeIconPy) {
        $pythonExe = Find-Python
        if ($pythonExe) {
            $output = & $pythonExe $MakeIconPy 2>&1
            if (Test-Path $IconFile) {
                Write-Host "  [OK] Icon generated successfully." -ForegroundColor Green
            } else {
                Write-Host "  [WARN] Icon generation failed - falling back to system icon." -ForegroundColor Yellow
                Write-Host "         $output" -ForegroundColor DarkGray
            }
        } else {
            Write-Host "  [WARN] Python not found - falling back to system icon." -ForegroundColor Yellow
        }
    } else {
        Write-Host "  [WARN] make_icon.py not found - falling back to system icon." -ForegroundColor Yellow
    }
} else {
    Write-Host "  [OK] Using existing icon: build\builder_icon.ico" -ForegroundColor Green
}

# ── Build the shortcut ────────────────────────────────────────────────────────

# The shortcut calls PowerShell invisibly; PowerShell opens Chrome.
# -WindowStyle Hidden means no PowerShell console window appears.
$psArgs = "-WindowStyle Hidden -ExecutionPolicy Bypass -NonInteractive " +
          "-File `"$LauncherPs1`""

$WshShell = New-Object -ComObject WScript.Shell
$lnk = $WshShell.CreateShortcut($ShortcutPath)

$lnk.TargetPath       = "powershell.exe"
$lnk.Arguments        = $psArgs
$lnk.WorkingDirectory = $ScriptDir
$lnk.Description      = "Start Build Dashboard server and open it in Chrome"
$lnk.WindowStyle      = 1   # 1 = Normal (PowerShell hides itself via -WindowStyle Hidden)

# ── Icon selection ────────────────────────────────────────────────────────────

$iconChosen = $false

# 1st choice: custom amber-gear icon generated by make_icon.py
if (Test-Path $IconFile) {
    $lnk.IconLocation = "$IconFile,0"
    $iconChosen = $true
}

# 2nd choice: wrench/settings icon from imageres.dll (Windows 10/11, index 109)
if (-not $iconChosen) {
    $imageres = "$env:SystemRoot\System32\imageres.dll"
    if (Test-Path $imageres) {
        $lnk.IconLocation = "$imageres,109"
        $iconChosen = $true
    }
}

# 3rd choice: globe icon from shell32.dll (always present)
if (-not $iconChosen) {
    $lnk.IconLocation = "$env:SystemRoot\System32\shell32.dll,14"
}

$lnk.Save()

# ── Verify ────────────────────────────────────────────────────────────────────

if (Test-Path $ShortcutPath) {
    Write-Host ""
    Write-Host "  [OK] Shortcut created successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "       $ShortcutPath" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  How to use:" -ForegroundColor Yellow
    Write-Host "    * Double-click the shortcut to launch the Build Dashboard" -ForegroundColor White
    Write-Host "    * Chrome (or your default browser) will open automatically" -ForegroundColor White
    Write-Host "    * The server runs minimised on port 5001 in your taskbar" -ForegroundColor White
    Write-Host "    * Close the 'Build Dashboard Server' taskbar window to stop it" -ForegroundColor White
    Write-Host ""
    Write-Host "  Tip: the main Job Tracker app (port 5000) and Build Dashboard" -ForegroundColor DarkGray
    Write-Host "       (port 5001) can run at the same time without conflict." -ForegroundColor DarkGray
    Write-Host ""
} else {
    Write-Host "  [ERROR] Shortcut file was not created. Check permissions." -ForegroundColor Red
    Write-Host ""
    Read-Host "  Press Enter to exit"
    exit 1
}

# Offer to open Explorer at the Desktop
$answer = Read-Host "  Open Desktop folder now? (Y/n)"
if ($answer -eq "" -or $answer -match '^[Yy]') {
    Start-Process explorer.exe -ArgumentList ("/select," + $ShortcutPath)
}
Write-Host ""
